# Generated by Django 3.1.7 on 2021-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todocomp', '0003_auto_20210509_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importancy_level',
            field=models.CharField(choices=[('Regular', 'regular'), ('Important', 'important')], default='Regular', max_length=20),
        ),
    ]
