# Generated by Django 3.1.7 on 2021-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todocomp', '0004_todo_importancy_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_parameter',
            new_name='todo_text',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
